### ISSUE TITLE
Vercel throws error NO_RESPONSE_FROM_FUNCTION

### ISSUE THREAD

**Issue by Kiho** [echobind/bisonapp#126]
create bison-app installs prisma 2.8.1, hence it throws 502 on login 
https://github.com/prisma/prisma-client-js/issues/907

**Comment by cball** [comment]
Prisma should be upgraded to fix this: https://github.com/prisma/prisma/releases

**Comment by cball** [comment]
thanks for the heads up @Kiho!

**Comment by Kiho** [comment]
Thanks for nice project. I was not able to use latest version of prisma but 2.9.0 working fine with vercel.

**Comment by cball** [comment]
Glad it was helpful for you. 👍 We'll be taking a look at this in the next few days

**Comment by cball** [comment]
Prisma was upgraded, so this should be fixed.
