### ISSUE TITLE
sign up: TypeError: resolver is not a function

### ISSUE THREAD

**Issue by rburgst** [echobind/bisonapp#148]
created the app as in the tutorial
did
```
yarn db:migrate
yarn dev
```
open the page http://localhost:3000
click on login
click on sign up
enter some information

then I see the following in the log: 

```
[NEXT] 🚀 Server ready at http://localhost:4000/graphql
[NEXT] TypeError: resolver is not a function
[NEXT]     at apiResolver (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/api-utils.js:8:7)
[NEXT]     at runMicrotasks (<anonymous>)
[NEXT]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
[NEXT]     at async DevServer.handleApiRequest (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/next-server.js:47:397)
[NEXT]     at async Object.fn (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/next-server.js:39:218)
[NEXT]     at async Router.execute (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/router.js:23:67)
[NEXT]     at async DevServer.run (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/next-server.js:49:494)
[NEXT]     at async DevServer.handleRequest (/Users/rainer/git/private/turnen/sports-bison/node_modules/next/dist/next-server/server/next-server.js:17:101)
```

**Comment by rburgst** [comment]
to me it looks like that the `/pages/api/graphql.ts` is not as expected with next.js, judging from other integration tutorials for how to integrate apollo with next.js 
* https://apuyou.io/blog/serverless-graphql-apollo-server-nextjs
* https://stackoverflow.com/questions/62105419/next-js-api-routes-with-type-graphql-error-resolver-is-not-a-function
looks like those guys are using `apollo-server-micro`

**Comment by rburgst** [comment]
this is the `graphql.ts`  file that got generated for me: 
```
import express from 'express';
import { ApolloServer } from 'apollo-server-express';

import { createContext } from '../../graphql/context';
import { schema } from '../../graphql/schema';

export const GRAPHQL_PATH = '/api/graphql';

export const server = new ApolloServer({
  schema,
  playground: process.env.NODE_ENV !== 'production',
  introspection: true,
  context: createContext,
  cacheControl: true,
});

const app = express();
server.applyMiddleware({ app });

app.listen({ port: process.env.PORT || 4000 }, () =>
  console.log(`🚀 Server ready at http://localhost:4000${server.graphqlPath}`)
);
```

Note that this looks quite different from what the template suggests: https://github.com/echobind/bisonapp/blob/canary/packages/create-bison-app/template/pages/api/graphql.ts

**Comment by rburgst** [comment]
note that I chose the heroku setup in the setup wizard. Not sure if that makes a difference. At any rate I am very confused why I got a seemingly wrong version of the templates.

**Comment by rburgst** [comment]
regenerated the app with the vercel setup and there I get the correct `graphql.ts`

**Comment by cball** [comment]
Hey @rburgst! Thanks for the feedback. We're actively working on some improvements and will make sure to check into this. We're also overdue for a release (the latest code is tagged with canary)

Let us know if you have questions on anything else.

**Comment by cmejet** [comment]
This is likely resolved with #163

**Comment by rburgst** [comment]
> This is likely resolved with #163

@cmejet the problem I had was with the outdated file `pages/api/graphql.ts` which included code that was not compatible with `next`. I tried `npx create-bison-app@canary myapp` as @cball suggested and that seems that this works properly now even if I choose the vercel setup.

**Comment by rburgst** [comment]
so IMHO the problem was fixed via https://github.com/echobind/bisonapp/pull/135/files#diff-ce708de14e13830b26e49f4e91c69d6f81c0d84f3776a5c057ff03b09aaf2b7cL1

**Comment by kgajera** [comment]
Looks like this has been resolved so I'm closing this issue.
