### ISSUE TITLE
create-bison-app does not execute on node 16+

### ISSUE THREAD

**Issue by cball** [echobind/bisonapp#150]
Testing the canary release: Node 14 works fine, but Node 16 just installs and exits. We should update our Node matrix to test 16.

**Comment by kgajera** [comment]
Our `nodegit` dependency seems to be the only issue as they don't support node 16. Completing #149 is the best path forward.

**Comment by darleendenno** [comment]
Also doesn't work on Node 14+ -- Attempted to  create using both yarn & npx commands using 14.17.3 and received this error consistently:
![image](https://user-images.githubusercontent.com/17681528/126246783-934bc33b-e257-48f1-a1c2-a68655d301a0.png)

Switched back to 12, and worked like a dream ❤️
