### ISSUE TITLE
Running yarn test throws an authentication error 

### ISSUE THREAD

**Issue by guilhermedeandrade** [echobind/bisonapp#19]
I've successfully ran `yarn db:setup` and I have the `MyBysonApp_dev` database created with some tables such as Profile and User. However, when I try to run `yarn test` this error is thrown:

```sh
  ● Test suite failed to run

    Command failed: yarn prisma migrate up --create-db --experimental
    Environment variables loaded from prisma/.env
    Error: P1000: Authentication failed against database server at `localhost`, the provided database credentials for `postgres` are not valid.

    Please make sure to provide valid database credentials for the database server at `localhost`.
    error Command failed with exit code 1.
```

I've already changed both `prisma/.env` and `.env.test` files and added the user and password combination for my local postgres server.

Also, I did not face any issue by running `yarn prisma migrate up --create-db --experimental`

**Comment by cball** [comment]
@guilhermedeandrade if migrate works,  the `DATABASE_URL` value in `prisma/.env` is correct. Can you confirm the `DATABASE_URL` in `.env.test` is the same value?

**Comment by guilhermedeandrade** [comment]
The only difference is the name of the DB, which is either MyBisonApp_dev or MyBisonApp_test @cball 

`prisma/.env`: DATABASE_URL="postgresql://postgres:docker@localhost:5432/MyBisonApp_dev?schema=public"

`.env.test`
DATABASE_URL="postgresql://postgres:docker@localhost:5432/MyBisonApp_test?schema=public"

**Comment by cball** [comment]
thanks @guilhermedeandrade. I imagine we'll need to improve the setup a bit to handle different database configurations. We'll try and reproduce this and get back to you.

Is that postgres user a superuser?

**Comment by guilhermedeandrade** [comment]
> thanks @guilhermedeandrade. I imagine we'll need to improve the setup a bit to handle different database configurations. We'll try and reproduce this and get back to you.
> 
> Is that postgres user a superuser?

Yes, it is:

![image](https://user-images.githubusercontent.com/8797405/90341761-2099f480-dffa-11ea-8f5c-f1c8f9c6a6e6.png)

**Comment by cball** [comment]
@guilhermedeandrade this may be the culprit: https://github.com/echobind/bisonapp/blob/master/template/tests/jest.setup.js#L18.

Could you try changing that URL to `postgresql://postgres:docker@localhost:5432/MyBisonApp_test?schema=public` locally and see if that allows tests to run? If so, we'll work on a fix for it.

For background, this was put in as a way to ensure a completely fresh database by using a random schema. It should only be required if DATABASE_URL is not already set.

**Comment by guilhermedeandrade** [comment]
> @guilhermedeandrade this may be the culprit: [https://github.com/echobind/bisonapp/blob/master/template/tests/jest.setup.js#L18](https://github.com/echobind/bisonapp/blob/master/template/tests/jest.setup.js?rgh-link-date=2020-08-19T13%3A13%3A22Z#L18).
> 
> Could you try changing that URL to `postgresql://postgres:docker@localhost:5432/MyBisonApp_test?schema=public` locally and see if that allows tests to run? If so, we'll work on a fix for it.
> 
> For background, this was put in as a way to ensure a completely fresh database by using a random schema. It should only be required if DATABASE_URL is not already set.

Yes, that works! :tada: Didn't think about checking the `jest.setup.js` file

**Comment by cball** [comment]
🎉 awesome! We'll get working on a fix. Appreciate the help tracking it down.
