### ISSUE TITLE
Update template readme

### ISSUE THREAD

**Issue by kgajera** [echobind/bisonapp#198]
- The nexus code examples are outdated
- We should also explain how the code generation works
  -  It runs automatically on file changes through `yarn dev`
  - Can be run manually using `yarn build:types`

**Comment by darleendenno** [comment]
Thank you! I was confused as to if I needed to run `yarn codegen` in order to generate types.

PS @kgajera thank you for your work on this repo -- bisonapp is one of my faves ❤️
