### ISSUE TITLE
Try out Swimm.io

### ISSUE THREAD

**Issue by mcavaliere** [echobind/bisonapp#269]
Swimm is a tool that claims to auto-generate code documentation and keep it up to date. 

Let's attempt to integrate it, and gauge its usefulness. 

@mcavaliere and @cmejet are connected with their cofounder/rep, so we can get a trial extension if needed.

**Comment by mcavaliere** [comment]
Steps: 

* [ ] Start documenting with their editor
* [ ] Add CI config
* [ ] Continue documenting for a period, see how well the docs auto-update
* [ ] Add their VSCode plugin

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/147237/178017206-5931a142-20a2-4e36-a133-96d15019b0ac.png">

**Comment by kgajera** [comment]
Closing this per comment in this PR: https://github.com/echobind/bisonapp/pull/271#issuecomment-1256173839
