### ISSUE TITLE
[bug] prisma.disconnect -> prisma.$disconnect from generated bison app.

### ISSUE THREAD

**Issue by agustif** [echobind/bisonapp#57]
Hello guys, awesome boilerplate, I had to make a couple fixes to get my project generated with create-bison-app to build before deploying to vercel. But the stack and codebase looks rad so far!

Mainly prisma.disconnect() call on lib/prisma.ts wasn't using thhe new $disconnect() syntax.

I checked on your main repo code and the template seems to be alright now using the $ dollar sign before the fn name. Im not sure if the generated by me was using an older version of the code maybe?

Maybe then this can be closed and will be fixed once create-bison-app uses latest version from master branch.

lib/prisma.ts
 ```
}

export async function disconnect() {
-  await prisma.disconnect();
+ await prisma.$disconnect();

  return true;
}
```

**Comment by cball** [comment]
thanks @agustif! that's exactly why it doesn't use the $disconnect syntax. I imagine we'll get to this in the next day or so, but feel free to open up a PR if you'd like, there shouldn't be any issues using the latest prisma.

**Comment by agustif** [comment]
It seems OK to me on template code!
https://github.com/echobind/bisonapp/blob/6d7029a13bf85a3d09a03b7fe2894cd76554984e/template/lib/prisma.ts


Hey @cball  I wouldn't know where to open the PR! it seems to me it's alright in your template code.

Not sure if something needs updating on the template generation or something!

Awesome work and thanks again btw
