### ISSUE TITLE
[bug] import { ErrorOption } from '...dist/types/form' 

### ISSUE THREAD

**Issue by agustif** [echobind/bisonapp#59]
Typescript didn't like the import not being root

<img width="770" alt="Captura de pantalla 2020-09-27 a las 11 12 55" src="https://user-images.githubusercontent.com/6601142/94361164-96da4e00-00b2-11eb-9432-380b3dd9ea42.png">

**Comment by cball** [comment]
Looks like this is fixed in `main` and will be released in the next version. Thanks again @agustif for the heads up!
